// <auto-generated />
using System;
using AI.Nova.Server.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AI.Nova.Server.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505110748_UpdateDatabaseComments")]
    partial class UpdateDatabaseComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Addresses.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<string>("City")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("市");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("District")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("区");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("boolean")
                        .HasComment("默认地址");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("收货联系号码");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("邮政编码");

                    b.Property<string>("Province")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("省");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("收货人姓名");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("详细地址");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDefault");

                    b.ToTable("Addresses", null, t =>
                        {
                            t.HasComment("用户收货地址表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.AreaCodes.AreaCode", b =>
                {
                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<int?>("Category")
                        .HasColumnType("integer")
                        .HasComment("城乡分类代码 (如：111-主城区, 121-镇中心区, 220-村庄)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<short?>("Level")
                        .HasColumnType("smallint")
                        .HasComment("行政级别: 1：省；2：地级；3：县级；4：乡级； 5：村级");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("行政区域名称");

                    b.Property<long?>("Pcode")
                        .HasColumnType("bigint")
                        .HasComment("父级区划代码");

                    b.HasKey("Code");

                    b.HasIndex("Pcode");

                    b.ToTable("AreaCodes", t =>
                        {
                            t.HasComment("行政区划代码表：存储各级行政区域信息及层级关系");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasComment("附件类型：0：用户头像小图,；1：用户头像原图,；2：商品中图,；3：商品原图");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasComment("附件路径");

                    b.HasKey("Id", "Kind");

                    b.ToTable("Attachments", t =>
                        {
                            t.HasComment("附件表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Carts.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("商品外键");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("数量");

                    b.Property<bool?>("Selected")
                        .HasColumnType("boolean")
                        .HasComment("是否选中");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasComment("购物车");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasComment("颜色如 #FF5733");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("名称");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasComment("商品分类表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Chatbot.SystemPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<string>("Markdown")
                        .HasColumnType("text")
                        .HasComment("内容");

                    b.Property<int?>("PromptKind")
                        .HasColumnType("integer")
                        .HasComment("类别，0：Support");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PromptKind")
                        .IsUnique();

                    b.ToTable("SystemPrompts", t =>
                        {
                            t.HasComment("系统提示词表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasComment("并发标记");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("名称");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("标准化名称");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", null, t =>
                        {
                            t.HasComment("角色表");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff71671-a1d6-5f97-abb9-d87d7b47d6e7"),
                            ConcurrencyStamp = "8ff71671-a1d6-5f97-abb9-d87d7b47d6e7",
                            Name = "s-admin",
                            NormalizedName = "S-ADMIN"
                        },
                        new
                        {
                            Id = new Guid("9ff71672-a1d5-4f97-abb7-d87d6b47d5e8"),
                            ConcurrencyStamp = "9ff71672-a1d5-4f97-abb7-d87d6b47d5e8",
                            Name = "demo",
                            NormalizedName = "DEMO"
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("声明类型");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("声明值");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色外键");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ClaimType", "ClaimValue");

                    b.ToTable("RoleClaims", null, t =>
                        {
                            t.HasComment("角色声明表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasComment("登录失败尝试次数");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("出生日期");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasComment("并发戳");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("除时间");

                    b.Property<DateTimeOffset?>("ElevatedAccessTokenRequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Elevated Access请求时间");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("邮件地址");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("邮箱是否已确认");

                    b.Property<DateTimeOffset?>("EmailTokenRequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("邮箱验证时间");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasComment("全名");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasComment("性别");

                    b.Property<bool?>("HasProfilePicture")
                        .HasColumnType("boolean")
                        .HasComment("是否有头像");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasComment("是否允许用户被锁定");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("锁定期结束时间");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("邮件地址");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("标准化用户名");

                    b.Property<DateTimeOffset?>("OtpRequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("一次性密码 (OTP) 的请求时间");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasComment("密码");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasComment("电话号码");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("电话号码是否已确认");

                    b.Property<DateTimeOffset?>("PhoneNumberTokenRequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("手机号时间");

                    b.Property<DateTimeOffset?>("ResetPasswordTokenRequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("重置密码时间");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasComment("安全戳");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasComment("是否启用双因素认证 (2FA)");

                    b.Property<DateTimeOffset?>("TwoFactorTokenRequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("双因素认证 (2FA) 时间");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasComment("用户表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("声明类型");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("声明值");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClaimType", "ClaimValue");

                    b.ToTable("UserClaims", null, t =>
                        {
                            t.HasComment("用户声明表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("提供商名称（例如：'Google', 'Facebook', 'Microsoft'）");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("提供商");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("提供商名称");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", null, t =>
                        {
                            t.HasComment("用户登录表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("用户外键");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("角色外键");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("UserRoles", null, t =>
                        {
                            t.HasComment("用户角色表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasComment("地理位置信息");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasComment("版本号");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CultureName")
                        .HasColumnType("text")
                        .HasComment("当前语言");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text")
                        .HasComment("设备详细信息");

                    b.Property<string>("IP")
                        .HasColumnType("text")
                        .HasComment("IP");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<int?>("NotificationStatus")
                        .HasColumnType("integer")
                        .HasComment("推送通知状态，0：未配置；1：允许；2：静音");

                    b.Property<int?>("PlatformType")
                        .HasColumnType("integer")
                        .HasComment("客户端应用平台类型（如：0：Web, 1：Ios,2：MacOS,3：Linux, 4：Android,5：Windows）");

                    b.Property<bool?>("Privileged")
                        .HasColumnType("boolean")
                        .HasComment("访问标记");

                    b.Property<long?>("RenewedOn")
                        .HasColumnType("bigint")
                        .HasComment("续期时间");

                    b.Property<string>("SignalRConnectionId")
                        .HasColumnType("text")
                        .HasComment("连接ID");

                    b.Property<long?>("StartedOn")
                        .HasColumnType("bigint")
                        .HasComment("开始时间");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用话外键");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", t =>
                        {
                            t.HasComment("用户会话表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("用户外键");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasComment("提供商（主键）：例如 'AspNetCore.Identity' 或 'Google'");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("名称（主键）：例如 'SecurityStamp' 或 'AccessToken'");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("软删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasComment("令牌值");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", null, t =>
                        {
                            t.HasComment("用户令牌表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.WebAuthnCredential", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea")
                        .HasComment("主键");

                    b.Property<Guid?>("AaGuid")
                        .HasColumnType("uuid")
                        .HasComment("认证器的 AAGUID，用于识别型号");

                    b.Property<byte[]>("AttestationClientDataJson")
                        .HasColumnType("bytea")
                        .HasComment("证明时的客户端数据 JSON 的原始二进制数据");

                    b.Property<string>("AttestationFormat")
                        .HasColumnType("text")
                        .HasComment("证明数据的格式 (如 packed, tpm)");

                    b.Property<byte[]>("AttestationObject")
                        .HasColumnType("bytea")
                        .HasComment("证明对象 (Attestation Object) 的原始 CBOR 数据");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsBackedUp")
                        .HasColumnType("boolean")
                        .HasComment("指示该凭证是否已被备份");

                    b.Property<bool?>("IsBackupEligible")
                        .HasColumnType("boolean")
                        .HasComment("指示该凭证是否具备备份资格");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea")
                        .HasComment("公钥");

                    b.Property<DateTimeOffset?>("RegDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("凭证注册的日期和时间");

                    b.Property<long?>("SignCount")
                        .HasColumnType("bigint")
                        .HasComment("签名计数器");

                    b.PrimitiveCollection<int[]>("Transports")
                        .HasColumnType("integer[]")
                        .HasComment("传输方式 (0：usb，1：nfc，2：ble，3：smart-card，4：hybrid，5，internal");

                    b.Property<byte[]>("UserHandle")
                        .HasColumnType("bytea")
                        .HasComment("关联到此凭证的用户的标识符");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WebAuthnCredentials", t =>
                        {
                            t.HasComment("凭据表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBases");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<byte[]>("Content")
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId");

                    b.ToTable("KnowledgeDocuments");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeDocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<int?>("Index")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("RawContent")
                        .HasColumnType("text");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("KnowledgeDocumentChunks");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid")
                        .HasComment("收货地址外键");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("抵扣总金额");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("订单编号");

                    b.Property<DateTimeOffset?>("PaidOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("支付时间");

                    b.Property<decimal?>("PayableAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("实际支付总金额");

                    b.Property<string>("Remark")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("备注");

                    b.Property<decimal?>("ShippingFee")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("配送费用");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("订单状态：0:待付款, 1:已付款, 2:已发货, 3:已完成, 4:已取消, 5:退款中");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("总价");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasComment("订单表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("订单外键");

                    b.Property<string>("PrimaryImageAltText")
                        .HasColumnType("text")
                        .HasComment("图片地址");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("商品外键");

                    b.Property<string>("ProductName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("商品名称");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("数量");

                    b.Property<decimal?>("SubTotal")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("总金额");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("单价");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasComment("订单子表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("实付金额");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("订单外键");

                    b.Property<DateTimeOffset?>("PaidOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("支付时间");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("支付方式 (如：Alipay, WeChatPay)");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("支付状态（0:待支付, 1:成功, 2:失败, 3:已退款）");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("交易单号");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasComment("支付流水表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("integer")
                        .HasComment("库存阈值");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("商品外键");

                    b.Property<int?>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasComment("预占库存数量");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer")
                        .HasComment("库存余量");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventories", null, t =>
                        {
                            t.HasComment("商品库存表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasComment("类别外键");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("DescriptionHTML")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasComment("HTML描述");

                    b.Property<string>("DescriptionText")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasComment("纯文本描述");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasComment("向量");

                    b.Property<bool?>("HasPrimaryImage")
                        .HasColumnType("boolean")
                        .HasComment("拥有主图片");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("名称");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasComment("价格");

                    b.Property<string>("PrimaryImageAltText")
                        .HasColumnType("text")
                        .HasComment("主图片 Alt Text");

                    b.Property<int>("ShortId")
                        .HasColumnType("integer")
                        .HasComment("商品短ID");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("商品表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<string>("AltText")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Alt Text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("图片路径");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasComment("是否封面主图");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("商品主键");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("排序");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", null, t =>
                        {
                            t.HasComment("商品图片表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("主键");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("评论内容");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasComment("是否匿名评论");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("订单外键");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("商品外键");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasComment("评分 (取值范围 1-5)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews", t =>
                        {
                            t.HasComment("商品评价表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.PushNotification.PushNotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("主键");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .HasColumnType("text")
                        .HasComment("认证密钥");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasComment("设备标识符");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasComment("推送地址");

                    b.Property<long?>("ExpirationTime")
                        .HasColumnType("bigint")
                        .HasComment("订阅过期时间（秒）");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("P256dh")
                        .HasColumnType("text")
                        .HasComment("加密公钥");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasComment("推送平台类型：'apns' (Apple), 'fcmV1' (Firebase), 'browser' (Web Push)");

                    b.Property<string>("PushChannel")
                        .HasColumnType("text")
                        .HasComment("推送渠道");

                    b.Property<long?>("RenewedOn")
                        .HasColumnType("bigint")
                        .HasComment("订阅续期时间 （秒）");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasComment("订阅标签数组[\"news\", \"alerts\"]");

                    b.Property<Guid?>("UserSessionId")
                        .HasColumnType("uuid")
                        .HasComment("用户会话外键");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId")
                        .IsUnique()
                        .HasFilter("'UserSessionId' IS NOT NULL");

                    b.ToTable("PushNotificationSubscriptions", t =>
                        {
                            t.HasComment("推送通知订阅表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Todo.TodoItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("主键ID：待办事项的唯一标识");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("删除者");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<bool?>("IsDone")
                        .HasColumnType("boolean")
                        .HasComment("完成状态：true表示已完成，false表示未完成");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("修改者");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("修改时间");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasComment("任务标题：待办事项的名称或简短描述");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("关联的用户ID：标识该任务属于哪位用户");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoItems", t =>
                        {
                            t.HasComment("待办事项表：存储用户的任务列表");
                        });
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpireAt");

                    b.HasIndex("Key", "Value");

                    b.ToTable("HangfireCounter", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireHash", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Field")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Field");

                    b.HasIndex("ExpireAt");

                    b.ToTable("HangfireHash", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvocationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExpireAt");

                    b.HasIndex("StateId");

                    b.HasIndex("StateName");

                    b.ToTable("HangfireJob", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJobParameter", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("JobId", "Name");

                    b.ToTable("HangfireJobParameter", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireList", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Position");

                    b.HasIndex("ExpireAt");

                    b.ToTable("HangfireList", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireLock", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HangfireLock", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireQueuedJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FetchedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Queue", "FetchedAt");

                    b.ToTable("HangfireQueuedJob", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireServer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Heartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Queues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Heartbeat");

                    b.ToTable("HangfireServer", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireSet", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Key", "Value");

                    b.HasIndex("ExpireAt");

                    b.HasIndex("Key", "Score");

                    b.ToTable("HangfireSet", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("HangfireState", "jobs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("主键");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("密钥名称");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasComment("密钥");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", null, t =>
                        {
                            t.HasComment("密钥存储表");
                        });
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Addresses.Address", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.AreaCodes.AreaCode", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.AreaCodes.AreaCode", null)
                        .WithMany()
                        .HasForeignKey("Pcode")
                        .HasConstraintName("FK_AreaCode_ParentCode");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Carts.CartItem", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.RoleClaim", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserClaim", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserLogin", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserRole", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserSession", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserToken", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.WebAuthnCredential", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("WebAuthnCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeDocument", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Knowledge.KnowledgeBase", "KnowledgeBase")
                        .WithMany("Documents")
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KnowledgeBase");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeDocumentChunk", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Knowledge.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Orders.Order", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Addresses.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Orders.OrderItem", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.Nova.Server.Api.Features.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Payments.Payment", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Orders.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.Inventory", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.Product", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.ProductImage", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Products.ProductReview", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Orders.Order", "Order")
                        .WithMany("ProductReviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Nova.Server.Api.Features.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.PushNotification.PushNotificationSubscription", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.UserSession", "UserSession")
                        .WithOne("PushNotificationSubscription")
                        .HasForeignKey("AI.Nova.Server.Api.Features.PushNotification.PushNotificationSubscription", "UserSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Todo.TodoItem", b =>
                {
                    b.HasOne("AI.Nova.Server.Api.Features.Identity.Models.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJob", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireState", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJobParameter", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireJob", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireQueuedJob", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireJob", "Job")
                        .WithMany("QueuedJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireState", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireJob", "Job")
                        .WithMany("States")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Addresses.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.Role", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Roles");

                    b.Navigation("Sessions");

                    b.Navigation("TodoItems");

                    b.Navigation("Tokens");

                    b.Navigation("WebAuthnCredentials");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Identity.Models.UserSession", b =>
                {
                    b.Navigation("PushNotificationSubscription");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeBase", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Knowledge.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AI.Nova.Server.Api.Features.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJob", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueuedJobs");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
